CREATE TABLE [bronze].[customer_churn] (

	[CustomerID] varchar(max) NULL, 
	[ChurnLabel] varchar(max) NULL, 
	[AccountLengthMonths] varchar(max) NULL, 
	[LocalCalls] varchar(max) NULL, 
	[LocalMins] varchar(max) NULL, 
	[IntlCalls] varchar(max) NULL, 
	[IntlMins] varchar(max) NULL, 
	[IntlActive] varchar(max) NULL, 
	[IntlPlan] varchar(max) NULL, 
	[ExtraInternationalCharges] varchar(max) NULL, 
	[CustomerServiceCalls] varchar(max) NULL, 
	[AvgMonthlyGBDownload] varchar(max) NULL, 
	[UnlimitedDataPlan] varchar(max) NULL, 
	[ExtraDataCharges] varchar(max) NULL, 
	[State] varchar(max) NULL, 
	[PhoneNumber] varchar(max) NULL, 
	[Gender] varchar(max) NULL, 
	[Age] varchar(max) NULL, 
	[Under30] varchar(max) NULL, 
	[Senior] varchar(max) NULL, 
	[IsGroup] varchar(max) NULL, 
	[NumberofCustomersinGroup] varchar(max) NULL, 
	[DeviceProtectionandOnlineBackup] varchar(max) NULL, 
	[ContractType] varchar(max) NULL, 
	[PaymentMethod] varchar(max) NULL, 
	[MonthlyCharge] varchar(max) NULL, 
	[TotalCharges] varchar(max) NULL, 
	[ChurnCategory] varchar(max) NULL, 
	[ChurnReason] varchar(max) NULL, 
	[LoadedAt] varchar(max) NULL
);